#! /bin/bash

echo "Installing stuff"
parts install php5 php5-apache2 php5-pdo-mysql php5-gd mysql composer

echo "starting things"
echo "parts start apache2 mysql" > ~/startup.sh
chmod +x ~/startup.sh
~/startup.sh

echo "installing drush"
composer global require drush/drush:6.*
echo "re open terminal after the script is complete to use drush"

echo "making drupal filesystem"
cd ~/
/home/codio/.composer/vendor/bin/drush -v dl drupal --drupal-project-rename="drupal"
cp -r drupal/. workspace/.
rm -rf drupal


pass=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 10 | head -n 1)
mysql -u root -e"create database codio; create user codio@localhost identified by '$pass'; grant usage on *.* to codio@localhost; grant all privileges on codio.* to codio@localhost"

echo "=============================="
echo "db credentials are as follows:"
echo ""
echo "user: codio"
echo "pass: $pass"
echo "db: codio"
echo ""
echo "=============================="

echo ""
echo "finishing up"


cp ~/workspace/sites/default/default.settings.php ~/workspace/sites/default/settings.php

echo "
\$databases['default']['default'] = array(
  'driver' => 'mysql',
  'database' => 'codio',
  'username' => 'codio',
  'password' => '$pass',
  'host' => 'localhost',
);
" >> ~/workspace/sites/default/settings.php

mkdir ~/workspace/sites/default/files

echo "all done"

